Create the home banking links and a new style for name
eldolar/web pull request #19
Opened 2020-10-22 15:46 UTC by SantiDepetris

Url for homebankings added
https://github.com/eldolar/web/issues/5

2020-10-23 07:17 UTC, edudepetris commented on src/components/Bank.js
> +      {name}
ident with 2 spaces.

2020-10-23 07:19 UTC, edudepetris commented on src/components/Bank.js
> +      {name}
I like your idea, don't change it 👍 

As alternative you can use a `<a>`

```jsx
<h1 ... >
  <a href={url}>{name}
```

2020-10-23 07:24 UTC, edudepetris commented on src/styles/Bank.module.scss
> +    color: blue;
what if we use another color like #C969CD
|#C969CD|
|-|
|<img width="323" alt="Screen Shot 2020-10-23 at 8 23 03 PM" src="https://user-images.githubusercontent.com/2192588/96968617-b9ef0500-156d-11eb-9b1e-af4be56ac915.png">|

2020-10-23 07:26 UTC, edudepetris requested changes
some tweaks!

2020-10-26 19:31 UTC, edudepetris commented on src/components/Bank.js
> +      {name}
@SantiDepetris ident with 2 spaces

2020-10-26 20:59 UTC, SantiDepetris commented on src/components/Bank.js
> +      {name}
Done

2020-10-31 01:09 UTC, edudepetris approved these changes

2020-10-31 01:09 UTC, merged